/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as PublicTncRouteImport } from './routes/_public/tnc'
import { Route as PublicPrivacyPolicyRouteImport } from './routes/_public/privacy-policy'
import { Route as MainSearchRouteImport } from './routes/_main/search'
import { Route as MainDiscussionsRouteImport } from './routes/_main/discussions'
import { Route as MainAdoptRouteImport } from './routes/_main/adopt'
import { Route as MainSettingsIndexRouteImport } from './routes/_main/settings/index'
import { Route as MainCommunityIndexRouteImport } from './routes/_main/community/index'
import { Route as MainCommunityCommunityIdRouteImport } from './routes/_main/community/$communityId'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const PublicTncRoute = PublicTncRouteImport.update({
  id: '/_public/tnc',
  path: '/tnc',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPrivacyPolicyRoute = PublicPrivacyPolicyRouteImport.update({
  id: '/_public/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSearchRoute = MainSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDiscussionsRoute = MainDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdoptRoute = MainAdoptRouteImport.update({
  id: '/adopt',
  path: '/adopt',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCommunityIndexRoute = MainCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCommunityCommunityIdRoute =
  MainCommunityCommunityIdRouteImport.update({
    id: '/community/$communityId',
    path: '/community/$communityId',
    getParentRoute: () => MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/adopt': typeof MainAdoptRoute
  '/discussions': typeof MainDiscussionsRoute
  '/search': typeof MainSearchRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/tnc': typeof PublicTncRoute
  '/community/$communityId': typeof MainCommunityCommunityIdRoute
  '/community/': typeof MainCommunityIndexRoute
  '/settings/': typeof MainSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/adopt': typeof MainAdoptRoute
  '/discussions': typeof MainDiscussionsRoute
  '/search': typeof MainSearchRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/tnc': typeof PublicTncRoute
  '/': typeof MainIndexRoute
  '/community/$communityId': typeof MainCommunityCommunityIdRoute
  '/community': typeof MainCommunityIndexRoute
  '/settings': typeof MainSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/adopt': typeof MainAdoptRoute
  '/_main/discussions': typeof MainDiscussionsRoute
  '/_main/search': typeof MainSearchRoute
  '/_public/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/_public/tnc': typeof PublicTncRoute
  '/_main/': typeof MainIndexRoute
  '/_main/community/$communityId': typeof MainCommunityCommunityIdRoute
  '/_main/community/': typeof MainCommunityIndexRoute
  '/_main/settings/': typeof MainSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adopt'
    | '/discussions'
    | '/search'
    | '/privacy-policy'
    | '/tnc'
    | '/community/$communityId'
    | '/community/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/adopt'
    | '/discussions'
    | '/search'
    | '/privacy-policy'
    | '/tnc'
    | '/'
    | '/community/$communityId'
    | '/community'
    | '/settings'
  id:
    | '__root__'
    | '/_main'
    | '/_main/adopt'
    | '/_main/discussions'
    | '/_main/search'
    | '/_public/privacy-policy'
    | '/_public/tnc'
    | '/_main/'
    | '/_main/community/$communityId'
    | '/_main/community/'
    | '/_main/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  PublicPrivacyPolicyRoute: typeof PublicPrivacyPolicyRoute
  PublicTncRoute: typeof PublicTncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_public/tnc': {
      id: '/_public/tnc'
      path: '/tnc'
      fullPath: '/tnc'
      preLoaderRoute: typeof PublicTncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/privacy-policy': {
      id: '/_public/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/search': {
      id: '/_main/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainSearchRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/discussions': {
      id: '/_main/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof MainDiscussionsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/adopt': {
      id: '/_main/adopt'
      path: '/adopt'
      fullPath: '/adopt'
      preLoaderRoute: typeof MainAdoptRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/': {
      id: '/_main/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/community/': {
      id: '/_main/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof MainCommunityIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/community/$communityId': {
      id: '/_main/community/$communityId'
      path: '/community/$communityId'
      fullPath: '/community/$communityId'
      preLoaderRoute: typeof MainCommunityCommunityIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAdoptRoute: typeof MainAdoptRoute
  MainDiscussionsRoute: typeof MainDiscussionsRoute
  MainSearchRoute: typeof MainSearchRoute
  MainIndexRoute: typeof MainIndexRoute
  MainCommunityCommunityIdRoute: typeof MainCommunityCommunityIdRoute
  MainCommunityIndexRoute: typeof MainCommunityIndexRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAdoptRoute: MainAdoptRoute,
  MainDiscussionsRoute: MainDiscussionsRoute,
  MainSearchRoute: MainSearchRoute,
  MainIndexRoute: MainIndexRoute,
  MainCommunityCommunityIdRoute: MainCommunityCommunityIdRoute,
  MainCommunityIndexRoute: MainCommunityIndexRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  PublicPrivacyPolicyRoute: PublicPrivacyPolicyRoute,
  PublicTncRoute: PublicTncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
